/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTestFormattingRouteImport } from './routes/_authenticated/test-formatting'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authAuthCallbackRouteImport } from './routes/(auth)/auth-callback'
import { Route as AuthenticatedVocationalTestIndexRouteImport } from './routes/_authenticated/vocational-test/index'
import { Route as AuthenticatedSchoolsIndexRouteImport } from './routes/_authenticated/schools/index'
import { Route as AuthenticatedResultsIndexRouteImport } from './routes/_authenticated/results/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedCareersIndexRouteImport } from './routes/_authenticated/careers/index'
import { Route as AuthenticatedSchoolsSchoolIdRouteImport } from './routes/_authenticated/schools/$schoolId'
import { Route as AuthenticatedResultsSessionIdRouteImport } from './routes/_authenticated/results/$sessionId'
import { Route as AuthenticatedCareersCareerIdRouteImport } from './routes/_authenticated/careers/$careerId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTestFormattingRoute =
  AuthenticatedTestFormattingRouteImport.update({
    id: '/test-formatting',
    path: '/test-formatting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthCallbackRoute = authAuthCallbackRouteImport.update({
  id: '/(auth)/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVocationalTestIndexRoute =
  AuthenticatedVocationalTestIndexRouteImport.update({
    id: '/vocational-test/',
    path: '/vocational-test/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchoolsIndexRoute =
  AuthenticatedSchoolsIndexRouteImport.update({
    id: '/schools/',
    path: '/schools/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultsIndexRoute =
  AuthenticatedResultsIndexRouteImport.update({
    id: '/results/',
    path: '/results/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCareersIndexRoute =
  AuthenticatedCareersIndexRouteImport.update({
    id: '/careers/',
    path: '/careers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchoolsSchoolIdRoute =
  AuthenticatedSchoolsSchoolIdRouteImport.update({
    id: '/schools/$schoolId',
    path: '/schools/$schoolId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultsSessionIdRoute =
  AuthenticatedResultsSessionIdRouteImport.update({
    id: '/results/$sessionId',
    path: '/results/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCareersCareerIdRoute =
  AuthenticatedCareersCareerIdRouteImport.update({
    id: '/careers/$careerId',
    path: '/careers/$careerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-callback': typeof authAuthCallbackRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/test-formatting': typeof AuthenticatedTestFormattingRoute
  '/careers/$careerId': typeof AuthenticatedCareersCareerIdRoute
  '/results/$sessionId': typeof AuthenticatedResultsSessionIdRoute
  '/schools/$schoolId': typeof AuthenticatedSchoolsSchoolIdRoute
  '/careers': typeof AuthenticatedCareersIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/results': typeof AuthenticatedResultsIndexRoute
  '/schools': typeof AuthenticatedSchoolsIndexRoute
  '/vocational-test': typeof AuthenticatedVocationalTestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-callback': typeof authAuthCallbackRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/test-formatting': typeof AuthenticatedTestFormattingRoute
  '/careers/$careerId': typeof AuthenticatedCareersCareerIdRoute
  '/results/$sessionId': typeof AuthenticatedResultsSessionIdRoute
  '/schools/$schoolId': typeof AuthenticatedSchoolsSchoolIdRoute
  '/careers': typeof AuthenticatedCareersIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/results': typeof AuthenticatedResultsIndexRoute
  '/schools': typeof AuthenticatedSchoolsIndexRoute
  '/vocational-test': typeof AuthenticatedVocationalTestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/auth-callback': typeof authAuthCallbackRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_authenticated/test-formatting': typeof AuthenticatedTestFormattingRoute
  '/_authenticated/careers/$careerId': typeof AuthenticatedCareersCareerIdRoute
  '/_authenticated/results/$sessionId': typeof AuthenticatedResultsSessionIdRoute
  '/_authenticated/schools/$schoolId': typeof AuthenticatedSchoolsSchoolIdRoute
  '/_authenticated/careers/': typeof AuthenticatedCareersIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/results/': typeof AuthenticatedResultsIndexRoute
  '/_authenticated/schools/': typeof AuthenticatedSchoolsIndexRoute
  '/_authenticated/vocational-test/': typeof AuthenticatedVocationalTestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-callback'
    | '/login'
    | '/register'
    | '/test-formatting'
    | '/careers/$careerId'
    | '/results/$sessionId'
    | '/schools/$schoolId'
    | '/careers'
    | '/dashboard'
    | '/profile'
    | '/results'
    | '/schools'
    | '/vocational-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-callback'
    | '/login'
    | '/register'
    | '/test-formatting'
    | '/careers/$careerId'
    | '/results/$sessionId'
    | '/schools/$schoolId'
    | '/careers'
    | '/dashboard'
    | '/profile'
    | '/results'
    | '/schools'
    | '/vocational-test'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(auth)/auth-callback'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_authenticated/test-formatting'
    | '/_authenticated/careers/$careerId'
    | '/_authenticated/results/$sessionId'
    | '/_authenticated/schools/$schoolId'
    | '/_authenticated/careers/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/profile/'
    | '/_authenticated/results/'
    | '/_authenticated/schools/'
    | '/_authenticated/vocational-test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authAuthCallbackRoute: typeof authAuthCallbackRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/test-formatting': {
      id: '/_authenticated/test-formatting'
      path: '/test-formatting'
      fullPath: '/test-formatting'
      preLoaderRoute: typeof AuthenticatedTestFormattingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth-callback': {
      id: '/(auth)/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof authAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vocational-test/': {
      id: '/_authenticated/vocational-test/'
      path: '/vocational-test'
      fullPath: '/vocational-test'
      preLoaderRoute: typeof AuthenticatedVocationalTestIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools/': {
      id: '/_authenticated/schools/'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof AuthenticatedSchoolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/': {
      id: '/_authenticated/results/'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/careers/': {
      id: '/_authenticated/careers/'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof AuthenticatedCareersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools/$schoolId': {
      id: '/_authenticated/schools/$schoolId'
      path: '/schools/$schoolId'
      fullPath: '/schools/$schoolId'
      preLoaderRoute: typeof AuthenticatedSchoolsSchoolIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/$sessionId': {
      id: '/_authenticated/results/$sessionId'
      path: '/results/$sessionId'
      fullPath: '/results/$sessionId'
      preLoaderRoute: typeof AuthenticatedResultsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/careers/$careerId': {
      id: '/_authenticated/careers/$careerId'
      path: '/careers/$careerId'
      fullPath: '/careers/$careerId'
      preLoaderRoute: typeof AuthenticatedCareersCareerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTestFormattingRoute: typeof AuthenticatedTestFormattingRoute
  AuthenticatedCareersCareerIdRoute: typeof AuthenticatedCareersCareerIdRoute
  AuthenticatedResultsSessionIdRoute: typeof AuthenticatedResultsSessionIdRoute
  AuthenticatedSchoolsSchoolIdRoute: typeof AuthenticatedSchoolsSchoolIdRoute
  AuthenticatedCareersIndexRoute: typeof AuthenticatedCareersIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedResultsIndexRoute: typeof AuthenticatedResultsIndexRoute
  AuthenticatedSchoolsIndexRoute: typeof AuthenticatedSchoolsIndexRoute
  AuthenticatedVocationalTestIndexRoute: typeof AuthenticatedVocationalTestIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTestFormattingRoute: AuthenticatedTestFormattingRoute,
  AuthenticatedCareersCareerIdRoute: AuthenticatedCareersCareerIdRoute,
  AuthenticatedResultsSessionIdRoute: AuthenticatedResultsSessionIdRoute,
  AuthenticatedSchoolsSchoolIdRoute: AuthenticatedSchoolsSchoolIdRoute,
  AuthenticatedCareersIndexRoute: AuthenticatedCareersIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedResultsIndexRoute: AuthenticatedResultsIndexRoute,
  AuthenticatedSchoolsIndexRoute: AuthenticatedSchoolsIndexRoute,
  AuthenticatedVocationalTestIndexRoute: AuthenticatedVocationalTestIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authAuthCallbackRoute: authAuthCallbackRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
